theme: minima
title: Daniel Oran
author: ""
description: ""

nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

header_pages:
  - index.md
  - about.md
  - contact.md
